# Generated by Django 4.2.30 on 2026-08-10 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_passwordexpiryreminderlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=80)),
                ('job_type', models.CharField(max_length=120)),
                ('task', models.CharField(max_length=255)),
                ('client_mutation_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=16)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('processed', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='async_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_AsyncJob',
                'managed': True,
            },
        ),
    ]
